import {
  BrowserKVStore,
  HttpAssetStore,
  HttpDocumentStore,
  type HttpAssetHeadersHook,
  type HttpDocumentHeadersHook,
} from '@openmaic/storage';
import { HttpRuntimeStore, type HttpRuntimeHeadersHook } from '@openmaic/storage/runtime/http';

import {
  assertDocumentStorageConfigurable,
  configureDocumentStorage,
  type DocumentStorageOptions,
} from '@/lib/document-store/config';
import {
  assertAssetPoolStorageConfigurable,
  configureAssetPoolStorage,
  type AssetPoolStorageOptions,
} from '@/lib/media/asset-pool-config';
import { assertRuntimeStorageConfigurable, configureRuntimeStorage } from '@/lib/runtime/config';
import { getLearnerKey } from '@/lib/runtime/learner-key';

let deviceKv: BrowserKVStore | undefined;
let learnerKeyPromise: Promise<string> | undefined;
let plIntegrationDetected = false;

const PL_SESSION_ATTEMPTS = 3;
const PL_SESSION_RETRY_DELAY_MS = 75;

export async function resolvePlPersistenceLearnerKey(): Promise<string | null> {
  for (let attempt = 0; attempt < PL_SESSION_ATTEMPTS; attempt += 1) {
    try {
      const response = await fetch('/api/pl/session', {
        credentials: 'include',
        cache: 'no-store',
      });
      if (response.headers.get('x-openmaic-pl-integrated') === '1') {
        plIntegrationDetected = true;
      }
      if (response.ok) {
        const body = await response.json() as { learnerKey?: unknown };
        if (typeof body.learnerKey === 'string' && /^pl:[a-f0-9]{64}$/.test(body.learnerKey)) {
          return body.learnerKey;
        }
      }
    } catch {
      // Ordinary standalone OpenMAIC use keeps its existing device identity.
    }
    if (attempt + 1 < PL_SESSION_ATTEMPTS) {
      await new Promise((resolve) => setTimeout(resolve, PL_SESSION_RETRY_DELAY_MS));
    }
  }
  return null;
}

export function isBrowserPersistenceEnabled(): boolean {
  return typeof window !== 'undefined' && process.env.NEXT_PUBLIC_PERSISTENCE === '1';
}

export function getPersistenceLearnerKey(): Promise<string> {
  if (!isBrowserPersistenceEnabled()) {
    return Promise.reject(new Error('Browser persistence is not enabled'));
  }
  return (learnerKeyPromise ??= resolvePlPersistenceLearnerKey()
    .then((key) => {
      if (key) return key;
      // A PL-integrated build must never create a second anonymous partition:
      // the server owns the signed learner identity and rejects mismatches.
      if (plIntegrationDetected) {
        throw new Error('Signed PL classroom session unavailable');
      }
      return getLearnerKey((deviceKv ??= new BrowserKVStore()));
    })
    .catch((error) => {
      learnerKeyPromise = undefined;
      throw error;
    }));
}

export async function getPersistenceRequestHeaders(): Promise<Record<string, string>> {
  if (!isBrowserPersistenceEnabled()) return {};
  // A PL handoff can happen through client navigation after the persistence
  // module has already memoized the anonymous device key. Re-check the signed
  // session for each request so runtime writes cannot remain stranded in the
  // anonymous partition after the learner has entered a classroom.
  const resolvedLearnerKey =
    (await resolvePlPersistenceLearnerKey()) ?? (await getPersistenceLearnerKey());
  const token = process.env.NEXT_PUBLIC_PERSISTENCE_TOKEN;
  return {
    'x-learner-key': resolvedLearnerKey,
    ...(token ? { authorization: `Bearer ${token}` } : {}),
  };
}

if (isBrowserPersistenceEnabled()) {
  const learnerKey = getPersistenceLearnerKey;
  const headers = getPersistenceRequestHeaders;

  const runtimeOptions = {
    store: () =>
      new HttpRuntimeStore({
        baseUrl: '/api/persistence',
        headers: headers satisfies HttpRuntimeHeadersHook,
      }),
    learnerKey,
  };
  const documentOptions: DocumentStorageOptions = {
    store: ({ validateScene, validateStage }) =>
      new HttpDocumentStore({
        baseUrl: '/api/persistence',
        headers: headers satisfies HttpDocumentHeadersHook,
        validateScene,
        validateStage,
      }),
  };
  // The document outlives the browser that produced it, so the media it
  // references must too: generated bytes go to the same endpoint under the
  // same credentials, and the document holds the id the pool allocated.
  // `serverBacked` is what tells local-cache cleanup that these refs are not
  // this browser's to delete.
  const assetOptions: AssetPoolStorageOptions = {
    store: () =>
      new HttpAssetStore({
        baseUrl: '/api/persistence',
        headers: headers satisfies HttpAssetHeadersHook,
      }),
    serverBacked: true,
  };
  try {
    // All checks are mutation-free. Once they pass, the synchronous configure
    // calls cannot leave only a subset of the persistence seams configured.
    assertRuntimeStorageConfigurable();
    assertDocumentStorageConfigurable();
    assertAssetPoolStorageConfigurable();
    configureRuntimeStorage(runtimeOptions);
    configureDocumentStorage(documentOptions);
    configureAssetPoolStorage(assetOptions);
  } catch (error) {
    console.error(
      'FATAL: server-backed persistence bootstrap failed; no storage seam changes were applied',
      error,
    );
  }
}
